### ISSUE TITLE
Symbol Overrides being reset in upload?

### ISSUE THREAD

**Issue by RussellBishop** [abynim/sketch-selective-upload#11]
I've just been sending some angry emails to Sketch about Sketch Cloud, basically saying that overrides on nested symbols aren't making their way onto Sketch Cloud.

The response I received was that it may be caused by a plugin and that I should test this.

I've started doing some testing and I think I may have found that Selective Upload is part of the problem here. I'll continue to look into it – but do you think this could be possible @abynim ?

**Comment by RussellBishop** [comment]
If it helps, the document I think I'm finding this issue in is a Cloud Document, so every time I save it does a new Selective Upload to sketch.cloud.

**Comment by RussellBishop** [comment]
For clarity here, I made a stupid error. I was using a Sketch Cloud document (using Sketch Teams), and had rolled back to a previous version.

Obviously, this version was a Selective Upload, which lost my whole Symbols page which broke all instances.

Really - the lesson here is DO NOT use Selective Upload if your original file is not backed up somewhere other than Sketch Cloud.

**Comment by abynim** [comment]
Thanks for the follow up. I've added a warning in the readme to mention the lesson from this experience 🙌
