### ISSUE TITLE
Prefix has no effect in Sketch 69

### ISSUE THREAD

**Issue by cooper-joe** [abynim/sketch-selective-upload#12]
Prefixing my artboards with the selective upload prefix (`--` in my case) has no effect in Sketch version 69. The plugin doesn't seem to have any effect.  The "artboards ignored..." message does not appear, and pages/artboards with the `--` prefix appear in sketch cloud.

### Maybe-useful details
- I tried existing documents and new documents, both had this issue.
- changing prefix had no effect

Thanks for this plugin - it really helps me work effectively with terrible connectivity.

**Comment by chuckmallott** [comment]
🙏  Please fix?! I'd pay $ for a plugin for this functionality that works even when Sketch updates to a new version. If you need help testing/QA, happy to help.

**Comment by abynim** [comment]
Just published a fix. Please update, then completely quit and restart Sketch, and try again. Sorry for the delay in getting this out, and thanks for logging the issue 🙏

**Comment by cooper-joe** [comment]
Thanks @abynim. I've updated, tested and can confirm this fixes the issue. Thanks again for this plugin 👍

**Comment by chuckmallott** [comment]
Thank you so much! You made my week! :)
