### ISSUE TITLE
Files are being uploaded despite prefix

### ISSUE THREAD

**Issue by moritzsalla** [abynim/sketch-selective-upload#5]
I've tried both symbols and regular pages. I'm running Sketch v67.1.

**Comment by abynim** [comment]
Looks like a few things have changed in Sketch 67. I've made updates in a separate branch here: https://github.com/abynim/sketch-selective-upload/tree/sketch-67-fixes

Could you please test the build from the branch and let me know if it works as expected? 

**Two important steps** :  
1. Please remember to completely quit and restart Sketch after updating the plugin. 
1. Please test with a backup document. Don't want you to lose any important data in case there are some issues.

**Comment by abynim** [comment]
I had a couple of people confirm the update works, so it's merged. Please open a new issue if you still run into issues. Thanks for reporting!
