### ISSUE TITLE
Exclusion non working on Sketch 68

### ISSUE THREAD

**Issue by FridayOddity** [abynim/sketch-selective-upload#7]
Hey there,

Thanks for this awesome plugin! The exclusion prefix doesn't seem to be working anymore on Version 68 (102490), my excluded artboard are still being pushed to SketchCloud :(

**Comment by abynim** [comment]
@FridayOddity Could you please try this build and let me know if it works as expected? https://github.com/abynim/sketch-selective-upload/archive/sketch-68-fixes.zip

It's working fine for me but some confirmation would be great before I merge and publish the update. Thanks!

**Comment by FridayOddity** [comment]
I just tested it and it's working again! Thanks you, this plugin is so useful!

**Comment by abynim** [comment]
Thanks for the confirmation!
