### ISSUE TITLE
Selective Upload not working after new sketch update

### ISSUE THREAD

**Issue by ajoseph90** [abynim/sketch-selective-upload#8]
Hello, its seems that the new update to sketch has disabled this function as it did last time, please can you make an update to the plugin, as its a great feature!

**Comment by abynim** [comment]
@ajoseph90 Could you please try this build and let me know if it works as expected? https://github.com/abynim/sketch-selective-upload/archive/sketch-68-fixes.zip

It's working fine for me but some confirmation would be great before I merge and publish the update. Thanks!

**Comment by ajoseph90** [comment]
Hi Abynim,

It works perfectly!! Thanks

Kind Regards,
Angela

*Angela Joseph*
graphic designer | pixelsandmash.com
<http://www.pixelsandmash.com/portfolio>
